# Generated by Django 4.2.7 on 2025-10-13 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=50)),
                ('metric_type', models.CharField(choices=[('accuracy', 'Accuracy'), ('precision', 'Precision'), ('recall', 'Recall'), ('f1_score', 'F1 Score'), ('auc', 'AUC'), ('mse', 'Mean Squared Error'), ('mae', 'Mean Absolute Error')], max_length=50)),
                ('metric_value', models.FloatField()),
                ('dataset_size', models.IntegerField()),
                ('training_date', models.DateTimeField()),
                ('validation_date', models.DateTimeField(blank=True, null=True)),
                ('model_parameters', models.JSONField(default=dict)),
                ('performance_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_name', 'model_version'], name='analytics_m_model_n_afd379_idx'), models.Index(fields=['metric_type'], name='analytics_m_metric__0c6770_idx'), models.Index(fields=['is_active'], name='analytics_m_is_acti_f844a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_messages_sent', models.IntegerField(default=0)),
                ('total_messages_received', models.IntegerField(default=0)),
                ('average_session_duration', models.DurationField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('risk_score', models.FloatField(default=0.0)),
                ('mood_volatility', models.FloatField(default=0.0)),
                ('chat_frequency', models.FloatField(default=0.0)),
                ('appointment_attendance_rate', models.FloatField(default=0.0)),
                ('goal_completion_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='analytics_u_user_id_a24cf9_idx'), models.Index(fields=['engagement_score'], name='analytics_u_engagem_491876_idx'), models.Index(fields=['risk_score'], name='analytics_u_risk_sc_dbd95b_idx'), models.Index(fields=['last_activity'], name='analytics_u_last_ac_6bb817_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('severe', 'Severe')], default='low', max_length=20)),
                ('risk_score', models.FloatField(default=0.0)),
                ('risk_factors', models.JSONField(default=list)),
                ('protective_factors', models.JSONField(default=list)),
                ('crisis_indicators', models.JSONField(default=list)),
                ('assessment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_assessment_due', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_assessments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assessment_date'],
                'indexes': [models.Index(fields=['user', '-assessment_date'], name='analytics_r_user_id_5b69d2_idx'), models.Index(fields=['overall_risk_level'], name='analytics_r_overall_af7c73_idx'), models.Index(fields=['follow_up_required'], name='analytics_r_follow__2448a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='PredictiveInsights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('mood_prediction', 'Mood Prediction'), ('risk_assessment', 'Risk Assessment'), ('engagement_forecast', 'Engagement Forecast'), ('trend_analysis', 'Trend Analysis'), ('intervention_recommendation', 'Intervention Recommendation')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('severity_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('predicted_outcome', models.TextField(blank=True)),
                ('recommended_actions', models.JSONField(default=list)),
                ('data_sources', models.JSONField(default=list)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictive_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='analytics_p_user_id_19d673_idx'), models.Index(fields=['insight_type'], name='analytics_p_insight_f39850_idx'), models.Index(fields=['severity_level'], name='analytics_p_severit_abfcc4_idx'), models.Index(fields=['is_active'], name='analytics_p_is_acti_cd0077_idx')],
            },
        ),
        migrations.CreateModel(
            name='MoodAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mood_score', models.FloatField()),
                ('mood_trend', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining'), ('volatile', 'Volatile')], default='stable', max_length=20)),
                ('predicted_mood', models.FloatField(blank=True, null=True)),
                ('mood_confidence', models.FloatField(default=0.0)),
                ('factors', models.JSONField(default=dict)),
                ('insights', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='analytics_m_user_id_27bf52_idx'), models.Index(fields=['mood_trend'], name='analytics_m_mood_tr_633b79_idx'), models.Index(fields=['predicted_mood'], name='analytics_m_predict_8c318a_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BehaviorMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('login_frequency', 'Login Frequency'), ('session_duration', 'Session Duration'), ('feature_usage', 'Feature Usage'), ('social_interaction', 'Social Interaction'), ('goal_setting', 'Goal Setting'), ('appointment_booking', 'Appointment Booking'), ('mood_logging', 'Mood Logging'), ('chat_engagement', 'Chat Engagement')], max_length=50)),
                ('metric_value', models.FloatField()),
                ('metric_unit', models.CharField(default='count', max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('context', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'metric_type', '-period_end'], name='analytics_b_user_id_505996_idx'), models.Index(fields=['metric_type', 'period_start', 'period_end'], name='analytics_b_metric__a6a41b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('weekly', 'Weekly Report'), ('monthly', 'Monthly Report'), ('quarterly', 'Quarterly Report'), ('custom', 'Custom Report')], default='weekly', max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('summary_data', models.JSONField(default=dict)),
                ('insights', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('charts_data', models.JSONField(default=dict)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='analytics_reports/%Y/%m/%d/')),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('generated_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_reports', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['generated_for', '-created_at'], name='analytics_a_generat_49ff3b_idx'), models.Index(fields=['report_type'], name='analytics_a_report__07a16b_idx'), models.Index(fields=['period_start', 'period_end'], name='analytics_a_period__da19c3_idx')],
            },
        ),
    ]
