# Generated by Django 4.2.7 on 2025-10-14 14:25

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moodanalytics',
            options={'ordering': ['-analysis_date']},
        ),
        migrations.RemoveIndex(
            model_name='moodanalytics',
            name='analytics_m_user_id_27bf52_idx',
        ),
        migrations.AlterUniqueTogether(
            name='moodanalytics',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='moodanalytics',
            name='analysis_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='moodanalytics',
            name='dominant_mood',
            field=models.CharField(default='neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='useranalytics',
            name='mood_entries_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='moodanalytics',
            unique_together={('user', 'analysis_date')},
        ),
        migrations.AddIndex(
            model_name='moodanalytics',
            index=models.Index(fields=['user', '-analysis_date'], name='analytics_m_user_id_daffa7_idx'),
        ),
        migrations.RemoveField(
            model_name='moodanalytics',
            name='date',
        ),
    ]
