# Generated by Django 4.2.7 on 2025-10-11 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_type', models.CharField(choices=[('mood_logging', 'Mood Logging'), ('chatting', 'Chatting'), ('goal_progress', 'Goal Progress'), ('appointment_attendance', 'Appointment Attendance')], max_length=25)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'streak_type')},
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('first_mood_log', 'First Mood Log'), ('consistent_logger', 'Consistent Logger'), ('chat_starter', 'Chat Starter'), ('helper', 'Helper'), ('goal_setter', 'Goal Setter'), ('progress_tracker', 'Progress Tracker'), ('appointment_booker', 'Appointment Booker'), ('feedback_giver', 'Feedback Giver'), ('community_builder', 'Community Builder'), ('mental_health_champion', 'Mental Health Champion')], max_length=30)),
                ('description', models.TextField()),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('icon', models.CharField(default='🏆', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement_type')},
            },
        ),
    ]
