# Generated by Django 4.2.7 on 2025-10-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_streak_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_achievement',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_appointment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_feedback',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_message',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_sound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_system',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
