# Generated by Django 4.2.7 on 2025-10-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_invoice_payment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['user', '-unlocked_at'], name='accounts_ac_user_id_9e3d72_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['achievement_type'], name='accounts_ac_achieve_a3cf50_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['blocker'], name='accounts_bl_blocker_8f03c2_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['blocked'], name='accounts_bl_blocked_e96dce_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['subscription', '-issue_date'], name='accounts_in_subscri_905a40_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='accounts_in_status_08f461_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='accounts_in_due_dat_309676_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='accounts_in_invoice_72c085_idx'),
        ),
        migrations.AddIndex(
            model_name='moodentry',
            index=models.Index(fields=['user', '-date'], name='accounts_mo_user_id_0af47f_idx'),
        ),
        migrations.AddIndex(
            model_name='moodentry',
            index=models.Index(fields=['date'], name='accounts_mo_date_6a7331_idx'),
        ),
        migrations.AddIndex(
            model_name='moodentry',
            index=models.Index(fields=['user', 'date'], name='accounts_mo_user_id_404984_idx'),
        ),
        migrations.AddIndex(
            model_name='moodentry',
            index=models.Index(fields=['-date'], name='accounts_mo_date_58ec98_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['subscription', '-payment_date'], name='accounts_pa_subscri_447e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='accounts_pa_status_8957e4_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='accounts_pa_payment_4005cd_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='accounts_pa_transac_94711a_idx'),
        ),
        migrations.AddIndex(
            model_name='streak',
            index=models.Index(fields=['user', 'streak_type'], name='accounts_st_user_id_1a0e32_idx'),
        ),
        migrations.AddIndex(
            model_name='streak',
            index=models.Index(fields=['last_activity_date'], name='accounts_st_last_ac_dd5138_idx'),
        ),
    ]
