# Generated by Django 4.2.7 on 2025-10-13 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_achievement_accounts_ac_user_id_9e3d72_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok')], max_length=20)),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('posted', 'Posted'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('post_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_so_user_id_8eb4b0_idx'), models.Index(fields=['platform'], name='accounts_so_platfor_7ae91f_idx'), models.Index(fields=['status'], name='accounts_so_status_e28106_idx'), models.Index(fields=['scheduled_time'], name='accounts_so_schedul_c9bdb9_idx')],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_access_token', models.TextField(blank=True, null=True)),
                ('facebook_token_expiry', models.DateTimeField(blank=True, null=True)),
                ('twitter_access_token', models.TextField(blank=True, null=True)),
                ('twitter_token_secret', models.TextField(blank=True, null=True)),
                ('instagram_access_token', models.TextField(blank=True, null=True)),
                ('linkedin_access_token', models.TextField(blank=True, null=True)),
                ('tiktok_access_token', models.TextField(blank=True, null=True)),
                ('sharing_enabled', models.BooleanField(default=True)),
                ('auto_share_achievements', models.BooleanField(default=False)),
                ('auto_share_milestones', models.BooleanField(default=False)),
                ('last_facebook_post', models.DateTimeField(blank=True, null=True)),
                ('last_twitter_post', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_integration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='accounts_so_user_id_89ebcf_idx'), models.Index(fields=['sharing_enabled'], name='accounts_so_sharing_4abfa0_idx')],
            },
        ),
        migrations.CreateModel(
            name='MoodDataShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok')], max_length=20)),
                ('shared_content', models.TextField()),
                ('post_id', models.CharField(blank=True, max_length=255, null=True)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('mood_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='accounts.moodentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-shared_at'],
                'indexes': [models.Index(fields=['user', '-shared_at'], name='accounts_mo_user_id_a821e9_idx'), models.Index(fields=['mood_entry'], name='accounts_mo_mood_en_0fed93_idx'), models.Index(fields=['platform'], name='accounts_mo_platfor_4f030e_idx'), models.Index(fields=['is_successful'], name='accounts_mo_is_succ_a987ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='CalendarIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_calendar_id', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_integration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='accounts_ca_user_id_0b878b_idx'), models.Index(fields=['is_connected'], name='accounts_ca_is_conn_2f7561_idx'), models.Index(fields=['last_sync'], name='accounts_ca_last_sy_49a104_idx')],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('appointment_type', models.CharField(choices=[('counseling', 'Counseling Session'), ('follow_up', 'Follow-up Session'), ('crisis', 'Crisis Intervention'), ('group', 'Group Session'), ('workshop', 'Workshop'), ('other', 'Other')], default='counseling', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('google_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.ForeignKey(limit_choices_to={'role': 'counselor'}, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_counselor_appointments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_date'],
                'indexes': [models.Index(fields=['user', '-scheduled_date'], name='accounts_ap_user_id_a7baa9_idx'), models.Index(fields=['counselor', '-scheduled_date'], name='accounts_ap_counsel_cdd40a_idx'), models.Index(fields=['status'], name='accounts_ap_status_d379ca_idx'), models.Index(fields=['scheduled_date'], name='accounts_ap_schedul_876e40_idx'), models.Index(fields=['appointment_type'], name='accounts_ap_appoint_2405aa_idx')],
            },
        ),
    ]
