# Generated by Django 4.2.7 on 2025-10-13 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_socialmediapost_socialmediaintegration_mooddatashare_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('system', 'System'), ('message', 'Message'), ('appointment', 'Appointment'), ('achievement', 'Achievement'), ('feedback', 'Feedback')], default='system', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_no_user_id_b37b35_idx'), models.Index(fields=['user', 'is_read'], name='accounts_no_user_id_a4ff2e_idx'), models.Index(fields=['notification_type'], name='accounts_no_notific_6d2f3e_idx'), models.Index(fields=['sent'], name='accounts_no_sent_c734f3_idx')],
            },
        ),
    ]
