# Generated by Django 4.2.7 on 2025-10-13 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('call_type', models.CharField(choices=[('counseling', 'Counseling Session'), ('group', 'Group Session'), ('workshop', 'Workshop'), ('peer_support', 'Peer Support')], default='counseling', max_length=20)),
                ('provider', models.CharField(choices=[('twilio', 'Twilio Video'), ('zoom', 'Zoom')], default='twilio', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='scheduled', max_length=20)),
                ('room_sid', models.CharField(blank=True, max_length=100, null=True)),
                ('meeting_id', models.CharField(blank=True, max_length=100, null=True)),
                ('join_url', models.URLField(blank=True, null=True)),
                ('start_url', models.URLField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('max_participants', models.IntegerField(default=10)),
                ('recording_enabled', models.BooleanField(default=False)),
                ('chat_enabled', models.BooleanField(default=True)),
                ('waiting_room', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_calls', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='video_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_start'],
                'indexes': [models.Index(fields=['host', '-scheduled_start'], name='accounts_vi_host_id_990125_idx'), models.Index(fields=['status'], name='accounts_vi_status_6d4bd0_idx'), models.Index(fields=['scheduled_start'], name='accounts_vi_schedul_1390b0_idx'), models.Index(fields=['call_type'], name='accounts_vi_call_ty_5b430b_idx'), models.Index(fields=['provider'], name='accounts_vi_provide_8c803c_idx')],
            },
        ),
    ]
