# Generated by Django 4.2.7 on 2025-10-14 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_videocall'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('audio', 'Audio'), ('video', 'Video'), ('other', 'Other')], default='other', max_length=20)),
                ('file_size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('encryption_key', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='moodentry',
            name='mood_score',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key_id', models.CharField(max_length=100, unique=True)),
                ('secret_key', models.TextField()),
                ('service_name', models.CharField(max_length=50)),
                ('permissions', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('secret', models.TextField()),
                ('events', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_we_user_id_68eb25_idx'), models.Index(fields=['is_active'], name='accounts_we_is_acti_1d06d5_idx'), models.Index(fields=['last_triggered_at'], name='accounts_we_last_tr_26a39c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('max_downloads', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='accounts.fileattachment')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-shared_at'],
                'indexes': [models.Index(fields=['shared_by', '-shared_at'], name='accounts_sh_shared__391b52_idx'), models.Index(fields=['shared_with', '-shared_at'], name='accounts_sh_shared__fcc1cc_idx'), models.Index(fields=['expires_at'], name='accounts_sh_expires_5c3519_idx'), models.Index(fields=['is_active'], name='accounts_sh_is_acti_68739d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('message', 'New Message'), ('appointment', 'Appointment Reminder'), ('achievement', 'Achievement Unlocked'), ('system', 'System Notification'), ('mood_reminder', 'Mood Check-in Reminder'), ('feedback', 'Feedback Request')], default='system', max_length=20)),
                ('data', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user', '-sent_at'], name='accounts_pu_user_id_23b082_idx'), models.Index(fields=['user', 'is_read'], name='accounts_pu_user_id_57b146_idx'), models.Index(fields=['notification_type'], name='accounts_pu_notific_d0b41b_idx'), models.Index(fields=['scheduled_for'], name='accounts_pu_schedul_fc6d6b_idx'), models.Index(fields=['is_sent'], name='accounts_pu_is_sent_abfdd9_idx')],
            },
        ),
        migrations.CreateModel(
            name='OfflineData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=50)),
                ('data_id', models.CharField(max_length=100)),
                ('data_content', models.JSONField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'data_type', '-created_at'], name='accounts_of_user_id_aa2519_idx'), models.Index(fields=['user', 'is_synced'], name='accounts_of_user_id_402c38_idx'), models.Index(fields=['data_type', 'data_id'], name='accounts_of_data_ty_d16dcf_idx'), models.Index(fields=['device_id'], name='accounts_of_device__e3b63f_idx')],
                'unique_together': {('user', 'data_type', 'data_id', 'device_id')},
            },
        ),
        migrations.AddIndex(
            model_name='fileattachment',
            index=models.Index(fields=['uploaded_by', '-uploaded_at'], name='accounts_fi_uploade_b2d31f_idx'),
        ),
        migrations.AddIndex(
            model_name='fileattachment',
            index=models.Index(fields=['file_type'], name='accounts_fi_file_ty_c44f06_idx'),
        ),
        migrations.AddIndex(
            model_name='fileattachment',
            index=models.Index(fields=['uploaded_at'], name='accounts_fi_uploade_736afd_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['user', '-created_at'], name='accounts_ap_user_id_189362_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key_id'], name='accounts_ap_key_id_1a6706_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['service_name'], name='accounts_ap_service_1f8cb4_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['is_active'], name='accounts_ap_is_acti_5d74e9_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['expires_at'], name='accounts_ap_expires_658c35_idx'),
        ),
    ]
