# Generated by Django 5.2.7 on 2025-10-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_fileattachment_moodentry_mood_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='activities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='energy_level',
            field=models.CharField(blank=True, choices=[('1', '😴 Very Low'), ('2', '😪 Low'), ('3', '😐 Moderate'), ('4', '⚡ High'), ('5', '🔥 Very High')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='gratitude',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='intensity',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='triggers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='mood',
            field=models.CharField(choices=[('1', '😢 Very Sad'), ('2', '😕 Sad'), ('3', '😐 Neutral'), ('4', '😊 Happy'), ('5', '😄 Very Happy')], max_length=20),
        ),
    ]
