# Generated by Django 5.2.7 on 2025-10-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_resource_resources_r_created_83a7af_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload a file (PDF, image, video, audio, etc.)', null=True, upload_to='resources/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resource',
            name='attachment_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
    ]
